seed: 42
data:
  train_dir: "data/train"
  # Note that the image height and width must be proportionate to most of training data
  img_height: 32
  max_width: 192 #192 seems to be good middle ground
  grayscale: false
  num_workers: 8

train:
  batch_size: 32
  epochs: 40
  lr: 1e-3
  weight_decay: 1e-4
  grad_clip: 5.0
  lr_decay: 0.95

model:
  cnn_out_channels: 256
  lstm_hidden: 256
  lstm_layers: 1
  dropout: 0.3

log:
  print_every: 50
  ckpt_dir: "checkpoints_colour"
